<a href="https://colab.research.google.com/github/jclauss24/MLTSA25_JClauss/blob/main/In_Class_Code/MLTSA_lab_2_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
my_str = "hello"



In [2]:
my_str

'hello'

In [4]:
print(my_str)

hello


In [9]:
my_int = 6

In [10]:
my_float = 6.

In [11]:
print(my_float)

6.0


In [12]:
my_int * my_float

36.0

In [16]:
# multiplying a string by an integer will repeat that string the integer number of times
my_int * my_str

'hellohellohellohellohellohello'

In [17]:
# "adding" two strings together will concatenate them
helloworld = "Hello" + " World!"
helloworld

'Hello World!'

In [18]:
import numpy as np

In [36]:
my_nparr = np.array([1,2,3])
my_nparr

array([1, 2, 3])

In [20]:
# numpy arrays act like vectors
my_int * my_nparr

array([ 6, 12, 18, 24])

In [21]:
# boolean variables (true and false)
my_bool = True

In [22]:
0 == 1

False

In [23]:
my_int == 6

True

In [25]:
my_int != 6

False

In [26]:
# if else statements
if my_int != 6:
  print("my int is not 6")
else:
  print("my int is 6")

my int is 6


In [27]:
# to check the type of a variable
type(my_int)

int

In [31]:
# type is an ATTRIBUTE of the numpy array, not a method we call on the array
my_nparr.dtype

dtype('int64')

In [37]:
# max() is an example of a method we can call on our array
my_nparr.max()

3

In [38]:
my_nparr.argmax() # outputs the maximum index in the array

2

In [39]:
my_nparr

array([1, 2, 3])

In [40]:
my_nparr[0]

1

In [42]:
# both of these retrieve 3
my_nparr[2]
my_nparr[-1]

3

In [43]:
my_nparr[1:] # get index 1 to the end of the array

array([2, 3])

In [44]:
my_nparr[1:3] # the end of the range is excluded

array([2, 3])

In [45]:
list(range(1,4)) # again, end of the range is excluded

[1, 2, 3]

In [48]:
for a in range(1,4):
  print(a, sum(np.arange(0,a)).sum()) # np.arange returns numpy array with numbers from first parameter to second parameter

1 0
2 1
3 3


In [47]:
np.arange(0,a)

array([0, 1, 2])

In [54]:
# functions in python

def allodds(lastn):
  """
  prints odd numbers

  Input:
    lastn: (int) last number in the list
  Return:
    a list of odd numbers
  """
  odds = []
  for a in range(0,lastn + 1):
    if a % 2 == 1:
      odds.append(a)
    #print(odds) was used for testing

  return odds

In [50]:
# putting a question mark after a function will show you the docstring
allodds?

In [55]:
allodds(10)

[1, 3, 5, 7, 9]

In [82]:
def checkPalindrome(word):
  """
  Checks if the word given is a palindrome

  Input:
    word: (string) word that will be checked if it is a palindrome
  Return:
    True if the word is a palindrome, False if it is not
  """
  # could also use:
  #if type(word)==str: could have used this and an else statement instead of assert
  assert type(word) == str, "is not a string"
  if word == word[::-1].lower:
    # word[::-1] tells it to make a slice starting at the beginning and ending at the end
    # use .lower so that it will return true regardless of capitalization
    return True
  else: # don't technically need this else because return statement will exit the function
    return False



In [83]:
# to test the function, try an example for each outcome
# will return True
checkPalindrome("racecar")

True

In [84]:
# will return false
checkPalindrome("hello")

False

In [85]:
#will have an error because input is not a string
checkPalindrome(727)

AssertionError: is not a string